Controllers/PostaJobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BitirmeProj.Data;
using BitirmeProj.Models;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using BitirmeProj.Services;

namespace BitirmeProj.Controllers
{
    public class PostaJobController : Controller
    {
        // GET: Job/PostJob
        private readonly ApplicationDBContext _context;
        private readonly IConfiguration _configuration;
        private readonly IUserSessionService _userSessionService;

        public PostaJobController(ApplicationDBContext context, IConfiguration configuration,IUserSessionService userSessionService)
        {
            _context = context;
            _configuration = configuration;
            _userSessionService = userSessionService;
        }


        // GET: Jobs
        public async Task<IActionResult> Index()
        {
            return _context.JobListings != null ?
                       View(await _context.JobListings.ToListAsync()) :
                       Problem("Entity set 'ApplicationDBContext.Jobs'  is null.");
        }

        public IActionResult PostJob()
        {
            User currentUser = _userSessionService.GetCurrentUser();

            // Pass user data to the view
            ViewBag.CurrentUser = currentUser;

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PostJob(JobListing model)
        {
            System.Diagnostics.Debug.WriteLine("HERE!!!!");
            try
            {
                JobListing job = new JobListing();
                job.JobTitle = model.JobTitle;
                job.JobDescription = model.JobDescription;
                job.JobLocation = model.JobLocation;
                job.JobType = model.JobType;
                job.ApplicationDeadline = model.ApplicationDeadline;
                job.WorkPlaceType = model.WorkPlaceType;
                job.ExperienceLevel = model.ExperienceLevel;
                job.Salary = model.Salary;
                job.SalaryCurrency = model.SalaryCurrency;
                User currentUser = _userSessionService.GetCurrentUser();
                
                job.PostedBy = currentUser.UserID;
                job.IsActive = 1;
                job.JobCreatedDate = DateTime.Now;
                _context.JobListings.Add(job);
                _context.SaveChanges();

                TempData["SuccessMessage"] = "Job posted successfully";

                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("HERE error!");
                return Problem(ex.InnerException.Message);
            }

          
        }
    }
}

Views/PostaJob/Index.cshtml
@using BitirmeProj.Utilities;

@model IEnumerable<BitirmeProj.Models.JobListing>

@{
    ViewData["Title"] = "Post a Job";
}


<div  id="jobPostingModal" tabindex="-1" aria-labelledby="jobPostingModalLabel" >
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="jobPostingModalLabel">Post a Job</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id= "postJobForm" asp-action="PostJob" asp-controller="PostaJob" method="post">
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <label for="jobTitle">Job Title</label>
                        <input type="text" class="form-control" id="jobTitle" name="JobTitle" required>
                    </div>
                    <div class="form-group mb-3">
                        <label for="jobDescription" class="form-label">Job Description</label>
                        <textarea id="jobDescription" name="JobDescription"></textarea>
                    </div>



                    <div class="form-group">
                        <label for="applicationDeadline">Application Deadline</label>
                        <input type="date" class="form-control" id="applicationDeadline" name="ApplicationDeadline" required>
                    </div>
                    <div class="form-group">
                        <label for="jobLocationOption">Job Location</label>
                        <select id="jobLocationOption" class="form-select mt-2" name="JobLocation" required>
                            <option value="">Open this select menu</option>
                            @foreach (var kvp in BitirmeProj.Utilities.JobApplicationOptions.JobLocationOptions)
                            {
                                <option value="@kvp.Key">@kvp.Value</option>
                            }
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="jobtype">Job Type</label>
                        <select id="jobtype" class="form-select" name="JobType" required>
                            <option value="">Open this select menu</option>
                            @foreach (var kvp in BitirmeProj.Utilities.JobApplicationOptions.JobTypeOptions)
                            {
                                <option value="@kvp.Key">@kvp.Value</option>
                            }
                        </select>
                    </div>

               

                    <div class="form-group">
                        <label for="workPlaceType">Work Place Type</label>
                        <select id="workPlaceType" class="form-select" name="WorkPlaceType" required>
                            <option value="">Open this select menu</option>

                            @foreach (var kvp in BitirmeProj.Utilities.JobApplicationOptions.WorkPlaceTypeOptions)
                            {
                                <option value="@kvp.Key">@kvp.Value</option>
                            }
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="experienceLevel">Experience Level</label>
                        <select id="experienceLevel" class="form-select" name="ExperienceLevel" required>
                            <option value="">Open this select menu</option>

                            @foreach (var kvp in BitirmeProj.Utilities.JobApplicationOptions.ExperienceLevelOptions)
                            {
                                <option value="@kvp.Key">@kvp.Value</option>
                            }
                        </select>
                    </div>


                    <div class="form-group">
                        <label for="salary">Salary</label>
                        <input type="number" class="form-control" id="salary" name="Salary" required>
                    </div>


                    <div class="form-group">
                        <label for="salaryCurrency">Salary Currency</label>
                        <select id="salaryCurrency" class="form-select" name="SalaryCurrency" required>
                            <option value="">Open this select menu</option>

                            @foreach (var kvp in BitirmeProj.Utilities.JobApplicationOptions.SalaryCurrencyOptions)
                            {
                                <option value="@kvp.Key">@kvp.Value</option>
                            }
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Post Job</button>
                </form>
            </div>
        </div>
    </div>

    </div>

  
@{
    var message = TempData["SuccessMessage"] ?? string.Empty;
}

<script type="text/javascript">
    var message = '@message';
    if (message)
        alert(message);
</script>
<script src="https://cdn.tiny.cloud/1/4ejpm1kl43jkfk5tdpka6nj625zumegnbls3og2va1ls5f1x/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: '#jobDescription', // Target the textarea by its ID
        plugins: 'lists link',
        toolbar: 'undo redo | bold italic underline | bullist numlist | link',
        menubar: false
    });
</script>

Views/PostaJob/JobPostedSuccessfully.cshtml
<div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="successModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="successModalLabel">Success!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Job listing created successfully.</p>
            </div>
        </div>
    </div>
</div>